server:
  shutdown: graceful

spring:
  application:
    name: sendy-transfer-scheduler
  datasource:
    hikari:
      jdbc-url: ${SPRING_DATASOURCE_JDBC_URL:jdbc:mysql://localhost:3306/sendy}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${SPRING_DATASOURCE_USERNAME:sendy_master}
      password: ${SPRING_DATASOURCE_PASSWORD:sendy_master}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID}
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}


logging:
  level:
    org.hibernate.type: trace
    org.springframework.jdbc: trace