server:
  shutdown: graceful

spring:
  application:
    name: sendy-transfer-scheduler
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
      driver-class-name: org.h2.Driver
      username: sa
      password:
  kafka:
    consumer:
      group-id: reservation-transfer