name: Kotlin SpringBoot JUnit CI 
on:
  push:
    branches: [ "**" ]
    paths:
      - '**.kt'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'src/**'
  pull_request:
    branches: [ "**" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Run only tests
        run: ./gradlew test --stacktrace
